addSbtPlugin("org.scala-js" % "sbt-scalajs" % "1.10.1")
addSbtPlugin("ch.epfl.scala" % "sbt-scalajs-bundler" % "0.20.0")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
addSbtPlugin("ch.epfl.scala" % "sbt-release-early" % "2.1.1")
// addSbtPlugin("ohnosequences" % "sbt-github-release" % "0.7.1")
